global:
  scrape_interval: 15s

scrape_configs:
  # 1) Prometheus 자기 자신
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # 2) 우리 Django 웹
  - job_name: "jacommi_web"
    metrics_path: /metrics
    static_configs:
      - targets: ["web:8000"]